### ISSUE TITLE
upgrade v0.54.0

### ISSUE THREAD

**Issue by walejandromt** [zufardhiyaulhaq/frp-operator#2]
Hello, is it possible to update the operator to the latest version please?

**fatedier/frpc:v0.54.0**

https://github.com/zufardhiyaulhaq/frp-operator/blob/2f954b17159909fcf313354e0abc2bf40940d6fd/controllers/client_controller.go#L154C27-L154C34

**Comment by zufardhiyaulhaq** [comment]
update the master branch to v0.56.0
