### ISSUE TITLE
[BUG] Generated config.toml is incorrect

### ISSUE THREAD

**Issue by JinxCappa** [zufardhiyaulhaq/frp-operator#5]
**Describe the bug**
The generated config.toml file is not correct and the frpc container doesn't load the configuration

**To Reproduce**
Apply any config

**Expected behavior**
The client to start and load the correct parameters

**Screenshots or Logs**
Will do if requested

**Environment (please complete the following information):**
- OS: linux
- OS version: kubernetes 1.29
- frp-operator image version: 0.3.0

**Additional context**
The template for the config file is incorrect. I have a commit on a fork that fixed it for me. [aff69e5](https://github.com/JinxCappa/frp-operator/commit/aff69e5f5f60274f5c17b8c05c5a86ebaf14378d)

**Comment by zufardhiyaulhaq** [comment]
thanks @JinxCappa 
can you help submit the MR?
